apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibkr-trading_app-app
  namespace: trading_app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ibkr-trading_app-app
  template:
    metadata:
      labels:
        app: ibkr-trading_app-app
    spec:
      containers:
      - name: ibkr-trading_app-app
        image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}
        imagePullPolicy: Always
        env:
        - name: TRADING_MODEa
          valueFrom:
            configMapKeyRef:
              name: trading_app-config
              key: trading_mode
        volumeMounts:
        - name: trading_app-data
          mountPath: /app/trading_records
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: trading_app-data
        persistentVolumeClaim:
          claimName: trading_app-data-pvc
      - name: logs
        persistentVolumeClaim:
          claimName: logs-pvc
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: trading_app-config
  namespace: trading_app
data:
  trading_mode: "paper"  # Change to "live" for live trading_app
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trading_app-data-pvc
  namespace: trading_app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-pvc
  namespace: trading_app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: ibkr-trading_app-app
  namespace: trading_app
spec:
  selector:
    app: ibkr-trading_app-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080